### ISSUE TITLE
Composer Unable to install Imapi

### ISSUE THREAD

**Issue by ErikThiart** [mnapoli/imapi#11]
composer require mnapoli/imapi
Using version ^0.2.7 for mnapoli/imapi
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mnapoli/imapi ^0.2.7 -> satisfiable by mnapoli/imapi[0.2.7].
    - mnapoli/imapi 0.2.7 requires pear-pear.horde.org/horde_imap_client ~2.19 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by mnapoli** [comment]
I don't know what happened to that package unfortunately!

**Comment by ErikThiart** [comment]
Alright, so how do we go about to run your library? 
(I am a slight noob so sorry if this is off-topic, I assume the composer issue is related?)

**Comment by mnapoli** [comment]
I think I found it here: https://github.com/horde/Imap_Client It seems it's no longer registered on packagist and all the `pear-pear.horde.org/horde_*` packages have been removed from Packagist.

It will not be easy to fix unfortunately! I don't have much "open source" time to invest in this project at the moment. If your company is relying heavily on this and is blocked by this problem I can offer paid support to fix this (get in touch with me at matthieu at mnapoli dot fr). Else this will have to wait until I can dedicate some time to this issue.

**Comment by ErikThiart** [comment]
Just playing around, will see if I can find some time to fix it.

**Comment by mnapoli** [comment]
@ErikThiart wait I see this [on the install page of horde/Imap_Client](https://dev.horde.org/imap_client/install.php):

```json
{
    "repositories": [
        {
            "type": "pear",
            "url": "http://pear.horde.org"
        }
    ],
    "require": {
        "pear-pear.horde.org/Horde_Imap_Client": "*"
    }
}
```

Could you try adding the `repositories` section in `composer.json` and see if it works?

If it works then we can add it to the README.

**Comment by mnapoli** [comment]
Quick update, you can use HTTPS if necessary: `"url": "https://pear.horde.org"`

If anyone wants to send a pull request to add that information to the README that's great!

**Comment by zbateson** [comment]
This doesn't seem to be an issue any longer when I was going through installing and configuring.
